// Real analysis, not templating. Claude reads the full brief -- company,
// product, kind, vibe, style, usage, notes -- reasons about who this is
// for and what job the mascot needs to do, then writes the CREATIVE
// portion for 4 directions: form, personality expression, and a specific
// chosen color palette. The technical requirements (background, aspect
// ratio, no-outline rule, dimensional shading, style rendering language,
// avoid list, color-guard sentence) are NOT generated by Claude -- they're
// assembled here in code from the same fixed AVOID_BASE/STYLE_MAP used
// everywhere else, then appended to Claude's creative text.
//
// This replaces an earlier version that asked Claude to write 4 complete,
// fully self-contained prompts, each repeating the entire technical block
// verbatim. That was redundant generation four times over -- it took 43
// seconds and still got truncated even at max_tokens 3000. Asking for
// creative content only, technical assembly done in code, is faster,
// cheaper, and structurally can't truncate on the technical portion since
// that part isn't generated at all.

const { STYLE_MAP, AVOID_BASE } = require('./_prompt');

const ANTHROPIC_API_KEY = process.env.ANTHROPIC_API_KEY;
const ANTHROPIC_MODEL = 'claude-sonnet-5';

const TECHNICAL_ANGLES = [
  'a straightforward, on-brief read of the character',
  'an unexpected lateral twist on the form',
  'a bold, ownable single distinguishing feature',
  'the most surprising, screenshot-worthy version'
];

function buildTechnicalSuffix(styleText) {
  return `No outline, no black linework around shapes, colors meet directly. Real dimensional `
    + `shading, highlights and shadow shapes must be visible, never a flat solid-color silhouette, `
    + `but not heavy shadows or sharp specular highlights either. Style rendering: ${styleText}. `
    + `If a reference image is attached showing a plain colored sphere, that image is for shading `
    + `and rendering technique ONLY, its own color is irrelevant and must be completely ignored, `
    + `use the colors specified above instead. Full body, standing centered, facing the viewer, `
    + `default friendly expression. Flat solid pure white background, character fills 70% of frame `
    + `height. Single character only, no text, no logo, no watermark. Aspect ratio 1:1.`
    + `\n\nAvoid: ${AVOID_BASE}.`;
}

async function analyzeAndBuildPrompts(form) {
  const styleText = STYLE_MAP[form.style] || STYLE_MAP['Not sure yet'];

  const instruction = `You are Studiyo's character strategy director. Read this brief and think `
    + `about it before writing anything -- who uses this product, what feeling gap a mascot fills, `
    + `what visual territory competitors in this space probably already occupy, and what color `
    + `palette actually fits this specific brand and product. Decide the colors yourself, from `
    + `reasoning about the brief, not from any external reference.\n\n`
    + `Brief:\n`
    + `Company: ${form.company || 'n/a'}\n`
    + `Product: ${form.product || 'n/a'}\n`
    + `Mascot shape feel: ${(form.kind || []).join(', ') || 'Surprise us'}\n`
    + `Vibe: ${(form.vibe || []).join(', ') || 'friendly'}\n`
    + `Where it mostly lives: ${(form.usage || []).join(', ') || 'n/a'}\n`
    + `Notes: ${form.notes || 'none'}\n\n`
    + `For each of these 4 creative directions, write ONLY the creative concept, concise, 2-3 `
    + `sentences: the character's form and pose energy, its personality, and a specific named `
    + `color palette (real colors, not "brand colors"). Do NOT write background, lighting, or `
    + `technical instructions -- those are handled separately.\n\n`
    + `1. ${TECHNICAL_ANGLES[0]}\n2. ${TECHNICAL_ANGLES[1]}\n3. ${TECHNICAL_ANGLES[2]}\n`
    + `4. ${TECHNICAL_ANGLES[3]}\n\n`
    + `Respond ONLY with JSON, no markdown fences, no preamble:\n`
    + `{"briefAnalysis": "<2-3 sentences on the emotional job, the strategic opening, and why you `
    + `chose the palette you chose>", `
    + `"concepts": ["<concept 1>", "<concept 2>", "<concept 3>", "<concept 4>"]}`;

  const resp = await fetch('https://api.anthropic.com/v1/messages', {
    method: 'POST',
    headers: {
      'Content-Type': 'application/json',
      'x-api-key': ANTHROPIC_API_KEY,
      'anthropic-version': '2023-06-01'
    },
    body: JSON.stringify({
      model: ANTHROPIC_MODEL,
      max_tokens: 4096,
      messages: [{ role: 'user', content: instruction }]
    })
  });

  const data = await resp.json();

  if (!resp.ok || data.error) {
    const err = new Error(`Anthropic API error: ${data.error?.message || resp.statusText}`);
    err.status = 502;
    err.body = { httpStatus: resp.status, anthropicError: data.error || null };
    throw err;
  }

  const text = (data.content || []).map((c) => c.text || '').join('').trim();
  const clean = text.replace(/```json|```/g, '').trim();

  let parsed;
  try {
    parsed = JSON.parse(clean);
  } catch (e) {
    const err = new Error(`Brief analysis returned invalid JSON: ${e.message}`);
    err.status = 502;
    // Full raw response this time, not a derived preview -- the last two
    // fixes were both guesses about *why* text was missing/truncated, and
    // both turned out wrong. Showing the actual API response structure
    // directly removes the guessing entirely.
    err.body = {
      httpStatus: resp.status,
      anthropicError: data.error || null,
      stopReason: data.stop_reason,
      contentBlockTypes: (data.content || []).map((c) => c.type),
      rawResponse: JSON.stringify(data).slice(0, 1500)
    };
    throw err;
  }

  if (!Array.isArray(parsed.concepts) || parsed.concepts.length === 0) {
    throw new Error('Brief analysis returned no concepts');
  }

  const suffix = buildTechnicalSuffix(styleText);
  const prompts = parsed.concepts.map((concept) => `${concept}\n\n${suffix}`);

  return { briefAnalysis: parsed.briefAnalysis, prompts };
}

module.exports = { analyzeAndBuildPrompts };
